[2021-12-28 19:36:18,997] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: cleansing_dag.create_relational_db 2021-12-28T18:08:31.068607+00:00 [queued]>
[2021-12-28 19:36:19,009] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: cleansing_dag.create_relational_db 2021-12-28T18:08:31.068607+00:00 [queued]>
[2021-12-28 19:36:19,010] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2021-12-28 19:36:19,010] {taskinstance.py:1095} INFO - Starting attempt 1 of 2
[2021-12-28 19:36:19,011] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2021-12-28 19:36:19,026] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): create_relational_db> on 2021-12-28T18:08:31.068607+00:00
[2021-12-28 19:36:19,031] {standard_task_runner.py:52} INFO - Started process 102 to run task
[2021-12-28 19:36:19,034] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cleansing_dag', 'create_relational_db', '2021-12-28T18:08:31.068607+00:00', '--job-id', '194', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/kym_cleansing.py', '--cfg-path', '/tmp/tmpg_94fb39', '--error-file', '/tmp/tmpc944_wub']
[2021-12-28 19:36:19,035] {standard_task_runner.py:77} INFO - Job 194: Subtask create_relational_db
[2021-12-28 19:36:19,071] {logging_mixin.py:109} INFO - Running <TaskInstance: cleansing_dag.create_relational_db 2021-12-28T18:08:31.068607+00:00 [running]> on host 0b3e0a2afa7a
[2021-12-28 19:36:19,121] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cleansing_dag
AIRFLOW_CTX_TASK_ID=create_relational_db
AIRFLOW_CTX_EXECUTION_DATE=2021-12-28T18:08:31.068607+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-28T18:08:31.068607+00:00
[2021-12-28 19:36:19,228] {logging_mixin.py:109} WARNING - /opt/***/dags/kym_cleansing.py:230 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2021-12-28 19:36:19,235] {logging_mixin.py:109} WARNING - /opt/***/dags/kym_cleansing.py:233 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2021-12-28 19:36:19,612] {python.py:151} INFO - Done. Returned value was: None
[2021-12-28 19:36:19,625] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=cleansing_dag, task_id=create_relational_db, execution_date=20211228T180831, start_date=20211228T193618, end_date=20211228T193619
[2021-12-28 19:36:19,688] {local_task_job.py:151} INFO - Task exited with return code 0
