[2021-12-30 11:21:57,110] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: cleansing_dag.create_relational_db 2021-12-29T11:18:49.847884+00:00 [queued]>
[2021-12-30 11:21:57,126] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: cleansing_dag.create_relational_db 2021-12-29T11:18:49.847884+00:00 [queued]>
[2021-12-30 11:21:57,127] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2021-12-30 11:21:57,127] {taskinstance.py:1095} INFO - Starting attempt 1 of 2
[2021-12-30 11:21:57,128] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2021-12-30 11:21:57,148] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): create_relational_db> on 2021-12-29T11:18:49.847884+00:00
[2021-12-30 11:21:57,153] {standard_task_runner.py:52} INFO - Started process 13856 to run task
[2021-12-30 11:21:57,155] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cleansing_dag', 'create_relational_db', '2021-12-29T11:18:49.847884+00:00', '--job-id', '559', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/kym_cleansing.py', '--cfg-path', '/tmp/tmp__v72leu', '--error-file', '/tmp/tmpx1xxzpdz']
[2021-12-30 11:21:57,156] {standard_task_runner.py:77} INFO - Job 559: Subtask create_relational_db
[2021-12-30 11:21:57,194] {logging_mixin.py:109} INFO - Running <TaskInstance: cleansing_dag.create_relational_db 2021-12-29T11:18:49.847884+00:00 [running]> on host 06785b5b86ec
[2021-12-30 11:21:57,247] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cleansing_dag
AIRFLOW_CTX_TASK_ID=create_relational_db
AIRFLOW_CTX_EXECUTION_DATE=2021-12-29T11:18:49.847884+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-29T11:18:49.847884+00:00
[2021-12-30 11:21:57,366] {logging_mixin.py:109} WARNING - /opt/***/dags/kym_cleansing.py:234 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2021-12-30 11:21:57,368] {logging_mixin.py:109} WARNING - /opt/***/dags/kym_cleansing.py:235 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2021-12-30 11:21:57,374] {logging_mixin.py:109} WARNING - /opt/***/dags/kym_cleansing.py:238 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2021-12-30 11:21:57,729] {python.py:151} INFO - Done. Returned value was: None
[2021-12-30 11:21:57,740] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=cleansing_dag, task_id=create_relational_db, execution_date=20211229T111849, start_date=20211230T112157, end_date=20211230T112157
[2021-12-30 11:21:57,770] {local_task_job.py:151} INFO - Task exited with return code 0
